### ISSUE TITLE
Move Catel.Extensions.Prism6 to Orc.Prism6

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#1013]
@alexfdezsauco You want write access to these repositories?

**Comment by alexfdezsauco** [comment]
Yes

On Apr 28, 2017 10:31 AM, "Geert van Horrik" <notifications@github.com>
wrote:

@alexfdezsauco <https://github.com/alexfdezsauco> You want write access to
these repositories?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Catel/Catel/issues/1013>, or mute the thread

**Comment by GeertvanHorrik** [comment]
Done, see https://github.com/WildGums/Orc.Prism
