### ISSUE TITLE
Wrong behavior when closing a DataWindow when an exception is thrown

### ISSUE THREAD

**Issue by advapiIT** [Catel/Catel#1023]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Click on the ClickMe button
2. A DataWindow will show up, click on the OK button
3. An exception will be thrown and catched by IExceptionService
4. When you click the Close button even the DataWindow is closed

Platform:
.NET version: any

### Expected behaviour

The opened DataWindow shouldn't be closed

### Actual behaviour

It closes the exception one (correct) but also the DialogWindow (that should be kept opened instead)

Here's a sfw that shows the wrong behavior

[catel_exception_video.zip](https://github.com/Catel/Catel/files/1010281/catel_exception_video.zip)
[CatelDataWindowBackgroundIssue.zip](https://github.com/Catel/Catel/files/1010283/CatelDataWindowBackgroundIssue.zip)

**Comment by GeertvanHorrik** [comment]
I've been investigating this. This is actually not an issue in Catel but in your code. The reason this occurs is because you are showing the error message dialog **while the save is still in progress**. This means that the window will be created as **child** window of the window with the error. Thus if that window closes, all child windows automatically close as well.

You can either fix this by:

1. Setting the parent window manually of the error window
2. Update your exception handling code to use this (so it allows the window to close first):

```
private void GetExceptionHandling(IExceptionService exceptionService)
{
	exceptionService.Register<Exception>(async exception =>
	{
		var viewModelFactory = ServiceLocator.Default.ResolveType<IViewModelFactory>();
			var uiVisualizerService = ServiceLocator.Default.ResolveType<IUIVisualizerService>();

		var model = new ErrorMessageModel {Message = exception.Message};
			var viewModel = viewModelFactory.CreateViewModel<InnerTestDataViewModel>(model, null);

		var dispatcherService = ServiceLocator.Default.ResolveType<IDispatcherService>();
		dispatcherService.BeginInvoke(async () =>
		{
			await Task.Delay(50);
			await uiVisualizerService.ShowDialogAsync(viewModel);
		});
	});
}
```

Event better, consider using Orc.Notifications, I believe that always uses the main window (or none) as parent window.
