### ISSUE TITLE
Move Catel.MVVM collections to Catel.Core collections

### ISSUE THREAD

**Issue by bigworld12** [Catel/Catel#1507]
## Summary
currently we can't use ObservableDictionary or FastObservableCollection or any collection defined in Catel.MVVM in a .net standard project

## API Changes
move all the collections to Catel.Core project 

## Intended Use Case
using the collections outside of .net core applications

**Comment by vaecors** [comment]
@GeertvanHorrik I'm going to partially chime in on this so I hope you don't mind.

So moving both `FastObservableCollection` and `ObservableDictionary` to Catel.Core would not be a good idea and an unnecessary breaking change. That namespace is meant to be a target agnostic. 

The main issue with Catel.MVVM that is preventing it's use in .NET Standard libraries is this:

`<TargetFrameworks>net45;net46;net47;`**`netcoreapp3.0`**`;uap10.0.16299</TargetFrameworks>`

When it should realistically be this:

`<TargetFrameworks>net45;net46;`**`netstandard2.0;netstandard2.1`**`;uap10.0.16299</TargetFrameworks>`

.NET Standard 2.0 [supports .NET Framework 4.7 natively](https://github.com/dotnet/standard/issues/514) and .NET Standard 2.1 supports only .NET Core 3 so you'd have to add .NET Framework 4.8 as a target (pending in #1505).

I should also note that `ObservableDictionary` has an outstanding bug (#1506) so you should be aware of that.

**Comment by vaecors** [comment]
I don't agree with moving either `ObservableDictionary` or `FastObservableCollection` to Catel.Core. Aside from the fact it would be a major breaking change, it doesn't fit the scope of what Catel.Core tries to fill. 

The issue at hand is that Catel.MVVM targets **netcoreapp3.0** because it's technically a WPF User Control Library, not a Class Library. This is why you can't target it in a .NET Standard library because they cannot link back that way (it would be cyclical). 

Your library would essentially have to target netcoreapp3.0/3.1 in order to use Catel.MVVM in a lower level. 

A possible idea if @GeertvanHorrik could chime in would be to take a similar direction to what Microsoft has been doing with their libraries and start breaking them out into foundational libraries that could then do their minimal framework targeting. So for instance Catel.MVVM.Collections would be it's own library but targeting .NET Standard 2.0 (which has [native support](https://github.com/dotnet/standard/issues/514) for .NET Framework 4.7), .NET Standard 2.1 (.NET Core 3), .NET Framework 4.6 and .NET Framework 4.8 (there is not native support for .NET Core 3 for this afaik).

**Comment by bigworld12** [comment]
`ObservableDictionary` and `FastObservableCollection` are simply data structures, the only thing used in Catel.MVVM is the `IDispatcherService`.
That means we can create 2 variants of every data strcture
e.g. 
`ObservableDictionary`,`DispatcherObservableDictionary`
`FastObservableCollection` , `DispatcherFastObservableCollection`
i am in the process of creating a PR for the changes

**Comment by vaecors** [comment]
I still believe non-trivial endevor. `FastObservableCollection` depends on other components in Catel.MVVM such as `SuspensionContext<T>` which is also used by other components. Additionally `ObservableDictionary` needs to be fixed to use the same thing (see #1506) due to an outstanding bug. 

The amount of concerns that have to be moved to Catel.Core from Catel.MVVM means this probably wouldn't occur until 6.x because of the breaking nature of it.

**Comment by bigworld12** [comment]
since `SuspensionContext<T>` doesn't depend on anything in Catel.MVVM , i also moved it to Catel.Core

also , yes this is a breaking change, since e.g. users of the previous `FastObservableCollection` will need to rename it to `DispatcherFastObservableCollection` to maintain previous functionality.  

i will also be fixing the suppression bug for `ObservableDictionary`

**Comment by bigworld12** [comment]
also big thank you @vaecors I love your `ObservableDictionary` implmentation

**Comment by GeertvanHorrik** [comment]
Vnext will be 6.0 (unless hotfixes), so we could consider this. I am not sure about splitting up into lots of libraries, could over complicate the solution and management.

Current development branch represents 6.0. Will apply most of the simple changes such as breaking changes somewhere this week.

The collections can be moved to core, and we could keep the dispatchable versions in Catel.mvvm

**Comment by GeertvanHorrik** [comment]
The hotfixes have been released, we can start thinking about this again.

**Comment by rodpl** [comment]
Maybe another idea would be to move strict UI dependent classes and xamls into platform dedicated project liko Catel.Views.WPF and let Cattle.MVVM to become as net standard.

**Comment by GeertvanHorrik** [comment]
We did consider that, but at this stage we are only really interested in supporting WPF (and UWP) and in the future WinUI.

**Comment by GeertvanHorrik** [comment]
We want to wrap up the breaking changes for Catel 6.0 and this is one of the last ones on the list. Any input that you would like to share on this topic? 

1. What are the advantages of moving this to core
2. How should we deal with the dispatcher service

One of the options I have in mind is to move the `IDispatcherService` (interface + dummy implementation) to Catel.Core as well. Then we don't have to implement multiple classes for the collections and they could be used in the core library.

**Comment by ahmednfwela** [comment]
the idea is, collections are datastructures, so they shouldn't be tied to application projects (targeting net core)
and instead target a broader range of projects as a standard library

if IDispatcherService can be moved to core easily, that would be great

**Comment by GeertvanHorrik** [comment]
Added IDispatcherService to Catel.Core and implemented ShimDispatcherService (just executes the actions immediately). If Catel.MVVM is used, it will be using the actual DispatcherService for the correct platform.

**Comment by GeertvanHorrik** [comment]
Done. Closing this ticket, but feel free to comment / re-open if something is unclear.
