### ISSUE TITLE
Creating new SavableModelBase sets IsDirty to true

### ISSUE THREAD

**Issue by brattonr** [Catel/Catel#1540]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ X] .NET Standard
 - [ ] .NET Core

## Component

Catel.Core.SavableModelBase<>

## Version of Library
5.12.3

## Version of OS(s) listed above with issue
Windows 10 Build 1909

## Steps to Reproduce
1. Build project
2. Run unit tests.

## Expected Behavior
If I serialize an instance of SavableModelBase and then deserialize it, I expect all the values to remain identical.

## Actual Behavior
The IsDirty flag is being set to true when the instance is constructed, but is being changed to false after the instance is deserialized.

[Catel-IsDirtyTest.zip](https://github.com/Catel/Catel/files/4187576/Catel-IsDirtyTest.zip)

**Comment by GeertvanHorrik** [comment]
Copying unit tests to Catel.

**Comment by GeertvanHorrik** [comment]
The reason why `IsDirty` is `false` after deserialization is because it's coming from a clean (serialized) format. Internal Catel properties (such as IsDirty) are never being serialized.

There are a few things to do to overcome this:

1. Wrap IsDirty in a new property which will get serialized. You can then use this on deserialization to restore the IsDirty property
2. Override OnDeserialized en set IsDirty to true

**Comment by brattonr** [comment]
Thanks for taking the time to look at this.  I'll make adjustments to my unit tests.
