### ISSUE TITLE
ViewModel will not be added a second time to the ActiveViewModels Property of IViewModelManager

### ISSUE THREAD

**Issue by Marshmal2ow** [Catel/Catel#1776]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
Catel.MVVM

## Version of Library
5.12.11

## Version of OS(s) listed above with issue
win10 1909

## Steps to Reproduce
see attached Log =>  Line 101
[logfile.txt](https://github.com/Catel/Catel/files/6150845/logfile.txt)

## Expected Behavior
Assume that the ViewModel should be added in the IEnumerable<IViewModel> ActiveViewModels Property in the IViewModelManager when the specific Catel.UserControl has been loaded a second time. 
(I know, for my scenario I should use ViewModelLifetime.PartlyManual, but maybe I can share a bug.)
## Actual Behavior
ViewModel was not added to the IEnumerable<IViewModel> ActiveViewModel  Property in the IViewModelManager when the View is loaded a second time, otherwise when the view is loaded the first time then the ViewModel was listed in the ActiveViewModels  Property.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, we'll see if we can hotfix this on the 5.x branches. Do you also have a repro so we don't have to build it ourselves?

**Comment by Marshmal2ow** [comment]
Hey, I have just created a repo thats reproduce this bug.
Switch between tabs to see that effect.
See https://github.com/Marshmal2ow/CatelActiveViewModelsBug

**Comment by GeertvanHorrik** [comment]
Investigating.

My first observations:

1. The TabItem2 is correctly being re-registered (since Catel takes care of the lifetime management there)
2. The TabItem1 is not being re-registered since it's a manually injected view model

**Comment by GeertvanHorrik** [comment]
As soon as the view model (datacontext) is *not set explicitly*, it's behaving correctly. Big chance this is because of the "injected vm feature" (see https://github.com/Catel/Catel/blob/develop/src/Catel.MVVM/MVVM/Providers/UserControlLogic.cs#L644). The reason we introduced this feature is to support this scenario:

1. Window (with vm)
2. User control (can share same vm)

We did this to support showing the same view and view model as both user control and window.  

More information can be found here:

https://github.com/Catel/Catel/blob/develop/src/Catel.MVVM/MVVM/Providers/LogicBase.cs#L52

Will think about re-registering the vm after re-loading the vm.

**Comment by GeertvanHorrik** [comment]
The hard thing here is that view models have lifetime management. If the tab gets unloaded, the view model gets closed (save / cancel, etc). I don't feel comfortable customizing the lifetime management for this edge case.

A few alternatives:

1. Don't explicitly set the vm (let Catel handle it for you)
2. Use TabControl from Orc.Controls which keeps the tabs alive between switching (or at least allows you to specify the unload behavior of the TabControl)
