### ISSUE TITLE
CTL-757: Support CallerMemberName for platforms that support it

### ISSUE THREAD

**Issue by GeertvanHorrik** [Catel/Catel#749]
Jira issue originally created by user @geertvanhorrik:

Something like this:

```
protected internal void SetValue(
#if !NET40
[CallerMemberName]
#endif
string name, object value)
        {
            SetValue(name, value, true, true);
        }
```

Current locations:

* ModelBase.SetValue
* ModelBase.GetValue
* ObservableObject.RaisePropertyChanged

**Comment by GeertvanHorrik** [comment]
We dropped support for SL & .NET 4.0. This is probably now supported on all platforms, so we might need to look into this. @alexfdezsauco , can you investigate?

**Comment by GeertvanHorrik** [comment]
And make sure to double-check whether this results in a breaking change or not.

**Comment by alexfdezsauco** [comment]
Yes, I will investigate.

**Comment by alexfdezsauco** [comment]
Looks like we can introduce this without breaking change. 

I already added a couple of new methods to model base, just like this:

        [NotifyPropertyChangedInvocator]
        protected TValue Get<TValue>([CallerMemberName] string name = null)
        {
            return GetValue<TValue>(name);
        }

       [NotifyPropertyChangedInvocator]
        protected void Set(object value, bool notifyOnChange = true, [CallerMemberName] string name = null)
        {
            SetValue(name, value, notifyOnChange);
        }

And tested using a model implementation like this: 

    public class Person : ModelBase
    {
        public static PropertyData NameProperty = RegisterProperty("Name", typeof(string), string.Empty);

        public string Name
        {
            get => Get<string>();
            set => Set(value);
        }
    }

**Comment by GeertvanHorrik** [comment]
I am not sure whether I like the Set and Get (which derives from our GetValue and SetValue). Let me think about this one.

**Comment by DanielKuehner** [comment]
I came across this issue because a have already implemented the [CallerMemberName] attribute and wanted to switch to your ObservableObject but there I have missed it.

So I took a few minutes to transform your class and add [CallerMemberName] but I failed because of:
- A normal parameter with [CallerMemberName] becomes a optional parameter
- Thus moving the porpertName parameter to the end of the parameter list conflicts with existing overloads

In my opinion this might be a big breaking change across Catel and all using codes. Because on the one hand you could introduce other name methods or on the other hand you have to change the call stack because of rearranged parameters and additional methods to avoid same signatures because of object parameters.

Simple example:
`protected internal void RaisePropertyChanged(string propertyName, object newValue)`
gets
`protected internal void RaisePropertyChanged(object newValue, [CallerMemberName] string propertyName = "")`
but conflicts with
`protected internal void RaisePropertyChanged(object sender, string propertyName)`

But how to resolve this? Maybe we have to add all parameters like newValue and oldValue.

**Comment by GeertvanHorrik** [comment]
Yeah, that's why I'm not very confident in applying this code. For the ModelBase, it's not a big deal (we have Catel.Fody for that), but for ObservableObject, it gets a bit more complex. I need to think about this, but definitely not in 5.1 (we want to finalize that asap).

**Comment by GeertvanHorrik** [comment]
@alexfdezsauco is still still something we can introduce as a non-breaking change or shall we just remove this ticket ?
